#pragma once

// AUTO-GENERATED FROM settings.ini.
// Do not edit this file manually.

namespace GameConfig
{
    inline constexpr const wchar_t* Executables[] =
    {
        L"Stalker2-Win64-Shipping.exe",
    };

    inline constexpr const wchar_t* Files[] =
    {
        L"VIDEOS/NTSC/LOGO.mp4",
        L"VIDEOS/NTSC/LOGO_SPLASH.mp4",
    };

    inline constexpr bool NoIntroEnabled = false;
    inline constexpr bool ReplaceMode = true;
    inline constexpr unsigned int StartDelayMilliseconds = 0;
    inline constexpr unsigned int RestoreDelaySeconds = 30;
    inline constexpr const wchar_t* BackupSuffix = L".nointro_original";
    inline constexpr bool EnableLog = false;

    namespace AutoSkip
    {
        inline constexpr bool Enabled = true;
        inline constexpr unsigned int StartDelayMs = 0;
        inline constexpr unsigned int TotalRuntimeMs = 5000;
        inline constexpr unsigned int PressIntervalMs = 10;
        inline constexpr unsigned int KeyHoldMs = 0;
        inline constexpr unsigned int ForegroundStableMs = 50;
        inline constexpr unsigned int WaitForForegroundMs = 15000;
        inline constexpr unsigned int MinWindowWidth = 640;
        inline constexpr unsigned int MinWindowHeight = 360;
        inline constexpr unsigned int EnterAfterMs = 0;
        inline constexpr unsigned int EscapeAfterMs = 0;
        inline constexpr unsigned int MaxKeyPresses = 0;
        inline constexpr bool OnlyWhenGameForeground = true;
        inline constexpr const wchar_t* KeyboardKeys = L"SPACE,ENTER,ESCAPE";
    }
}